# Generated by Django 4.0 on 2024-04-14 18:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('first_parag_rich', ckeditor.fields.RichTextField(null=True)),
                ('second_parag_rich', ckeditor.fields.RichTextField(null=True)),
                ('third_parag_rich', ckeditor.fields.RichTextField(null=True)),
                ('forth_parag_rich', ckeditor.fields.RichTextField(null=True)),
                ('fifth_parag_rich', ckeditor.fields.RichTextField(null=True)),
                ('first_parag', models.CharField(max_length=2000)),
                ('second_parag', models.CharField(max_length=2000)),
                ('third_parag', models.CharField(max_length=2000)),
                ('forth_parag', models.CharField(max_length=2000)),
                ('fifth_parag', models.CharField(max_length=2000)),
                ('display_image', models.ImageField(upload_to='')),
                ('first_image', models.ImageField(null=True, upload_to='')),
                ('second_image', models.ImageField(null=True, upload_to='')),
                ('third_image', models.ImageField(null=True, upload_to='')),
                ('mid_title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('explanation', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('explanation', ckeditor.fields.RichTextField(null=True)),
                ('default_price', models.IntegerField(default=1000, null=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=300, null=True)),
                ('tour_duration', models.CharField(max_length=20, null=True)),
                ('has_guide', models.BooleanField(default=False, null=True)),
                ('has_wifi', models.BooleanField(default=False, null=True)),
                ('has_lunch', models.BooleanField(default=False, null=True)),
                ('has_shuttle', models.BooleanField(default=False, null=True)),
                ('currency', models.CharField(default='try', max_length=3, null=True)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.province')),
            ],
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('explanation_rich', ckeditor.fields.RichTextField(null=True)),
                ('explanation', models.TextField()),
                ('is_popular', models.BooleanField(default=False, null=True)),
                ('capacity', models.IntegerField()),
                ('extra', models.CharField(max_length=1000, null=True)),
                ('num_bathroom', models.IntegerField()),
                ('default_price', models.IntegerField(default=1000, null=True)),
                ('num_bed', models.IntegerField()),
                ('num_room', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=300, null=True)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('has_parking', models.BooleanField(default=False, null=True)),
                ('has_wifi', models.BooleanField(default=False, null=True)),
                ('has_breakfast', models.BooleanField(default=False, null=True)),
                ('has_cleaning_service', models.BooleanField(default=False, null=True)),
                ('has_pool', models.BooleanField(default=False, null=True)),
                ('has_reception', models.BooleanField(default=False, null=True)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.province')),
                ('type', models.ManyToManyField(to='main.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Yatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('explanation', ckeditor.fields.RichTextField(null=True)),
                ('default_price', models.IntegerField(default=1000, null=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('num_bathroom', models.IntegerField()),
                ('brand', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('made_year', models.CharField(max_length=4, null=True)),
                ('renovation_year', models.CharField(max_length=4, null=True)),
                ('cruising_capacity', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('num_rooms', models.IntegerField(null=True)),
                ('boarding_passanger_capacity', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('cenova', models.CharField(max_length=30, null=True)),
                ('main_sail', models.CharField(max_length=30, null=True)),
                ('num_engine', models.IntegerField(null=True)),
                ('engine_type', models.CharField(max_length=30, null=True)),
                ('fuel_cost', models.CharField(max_length=30, null=True)),
                ('fuel_type', models.CharField(max_length=30, null=True)),
                ('yatch_material', models.CharField(max_length=30, null=True)),
                ('num_rudder', models.IntegerField(null=True)),
                ('daily_cruise_duration', models.CharField(max_length=30, null=True)),
                ('daily_ac_duration', models.CharField(max_length=30, null=True)),
                ('engine_horse_power', models.CharField(max_length=30, null=True)),
                ('fuel_capacity', models.CharField(max_length=30, null=True)),
                ('waste_tank_capacity', models.CharField(max_length=30, null=True)),
                ('water_tank_capacity', models.CharField(max_length=30, null=True)),
                ('hall_height', models.CharField(max_length=30, null=True)),
                ('width', models.CharField(max_length=30, null=True)),
                ('water_draft', models.CharField(max_length=30, null=True)),
                ('currency', models.CharField(default='try', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YatchFeatureCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YatchPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.province')),
            ],
        ),
        migrations.CreateModel(
            name='YatchPriceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('yatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yatch')),
            ],
        ),
        migrations.CreateModel(
            name='YatchImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('yatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yatch')),
            ],
        ),
        migrations.CreateModel(
            name='YatchFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yatch_feature_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yatchfeaturecategories')),
            ],
        ),
        migrations.AddField(
            model_name='yatch',
            name='features',
            field=models.ManyToManyField(to='main.YatchFeature'),
        ),
        migrations.AddField(
            model_name='yatch',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.province'),
        ),
        migrations.AddField(
            model_name='yatch',
            name='services',
            field=models.ManyToManyField(to='main.Services'),
        ),
        migrations.AddField(
            model_name='yatch',
            name='type',
            field=models.ManyToManyField(to='main.YatchType'),
        ),
        migrations.AddField(
            model_name='yatch',
            name='yatch_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.yatchport'),
        ),
        migrations.AddField(
            model_name='yatch',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.zone'),
        ),
        migrations.CreateModel(
            name='VillaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.villa')),
            ],
        ),
        migrations.AddField(
            model_name='villa',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.zone'),
        ),
        migrations.CreateModel(
            name='TourPriceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ManyToManyField(to='main.TourType'),
        ),
        migrations.AddField(
            model_name='tour',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.zone'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('zip_code', models.CharField(default='', max_length=6)),
                ('completed', models.BooleanField(default=False)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.villa')),
            ],
        ),
        migrations.CreateModel(
            name='PriceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('min_nights', models.IntegerField(null=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.villa')),
            ],
        ),
    ]
