# Generated by Django 3.2.16 on 2023-01-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('explanation', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('extra', models.CharField(max_length=500, null=True)),
                ('num_bathroom', models.IntegerField()),
                ('num_bed', models.IntegerField()),
                ('num_room', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
    ]
