# Generated by Django 4.0 on 2024-04-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatch',
            name='boarding_passanger_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='cenova',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='cruising_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='daily_ac_duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='daily_cruise_duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='engine_horse_power',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='engine_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='features',
            field=models.ManyToManyField(blank=True, to='main.YatchFeature'),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='fuel_capacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='fuel_cost',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='hall_height',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='made_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='main_sail',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='num_engine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='num_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='num_rudder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='renovation_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='services',
            field=models.ManyToManyField(blank=True, to='main.Services'),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='type',
            field=models.ManyToManyField(blank=True, to='main.YatchType'),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='waste_tank_capacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='water_draft',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='water_tank_capacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='width',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='yatch_material',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yatch',
            name='yatch_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.yatchport'),
        ),
    ]
