# Generated by Django 3.2.16 on 2023-01-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.villa')),
            ],
        ),
    ]
