# Generated by Django 3.2.16 on 2023-01-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_villaimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='villaimages',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
