# Generated by Django 4.0 on 2024-04-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_yatch_boarding_passanger_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatchReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('zip_code', models.CharField(default='', max_length=6)),
                ('completed', models.BooleanField(default=False)),
                ('yatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yatch')),
            ],
        ),
    ]
