# Generated by Django 3.2.16 on 2023-01-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_villaimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='explanation',
            field=models.TextField(),
        ),
    ]
