# Generated by Django 4.0 on 2024-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_yatchreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatchpriceinterval',
            name='min_nights',
            field=models.IntegerField(null=True),
        ),
    ]
