# Generated by Django 4.0 on 2024-04-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_yatchpriceinterval_min_nights'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('explanation', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VillaFeatureCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='villa',
            name='currency',
            field=models.CharField(default='try', max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='VillaFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_internal', models.BooleanField(default=False, null=True)),
                ('yatch_feature_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.villafeaturecategories')),
            ],
        ),
        migrations.AddField(
            model_name='villa',
            name='cancellation_policy',
            field=models.ManyToManyField(blank=True, to='main.CancellationPolicy'),
        ),
        migrations.AddField(
            model_name='villa',
            name='features',
            field=models.ManyToManyField(blank=True, to='main.VillaFeature'),
        ),
    ]
