# Generated by Django 3.2.16 on 2023-01-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230126_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.villa')),
            ],
        ),
    ]
