# Generated by Django 4.0 on 2024-04-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cancellationpolicy_villafeaturecategories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villafeature',
            old_name='yatch_feature_categories',
            new_name='villa_feature_categories',
        ),
    ]
