# Generated by Django 3.2.16 on 2023-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='default_price',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
