# Generated by Django 3.2.16 on 2023-01-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_villa_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='zip_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
