# Generated by Django 3.2.16 on 2023-01-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230128_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('first_parag', models.CharField(max_length=2000)),
                ('second_parag', models.CharField(max_length=2000)),
                ('third_parag', models.CharField(max_length=2000)),
                ('forth_parag', models.CharField(max_length=2000)),
                ('fifth_parag', models.CharField(max_length=2000)),
                ('display_image', models.ImageField(upload_to='')),
                ('first_image', models.ImageField(null=True, upload_to='')),
                ('second_image', models.ImageField(null=True, upload_to='')),
                ('third_image', models.ImageField(null=True, upload_to='')),
                ('mid_title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
