# Generated by Django 3.2.16 on 2023-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='has_breakfast',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='has_cleaning_service',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='has_parking',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='has_pool',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='has_reception',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='has_wifi',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
