# Generated by Django 4.0 on 2024-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_type_villa_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='type',
        ),
        migrations.AddField(
            model_name='villa',
            name='type',
            field=models.ManyToManyField(to='main.Type'),
        ),
    ]
