# Generated by Django 4.0 on 2024-02-15 19:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_villa_type_villa_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='explanation_rich',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
