# Generated by Django 4.0 on 2024-02-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_multipleimages_villa_multiple_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='multiple_image',
        ),
        migrations.DeleteModel(
            name='MultipleImages',
        ),
    ]
